var STRINGS_ON_DIFFERENT_LANGUAGES = {
  EN: {
    YES: 'Yes',
    NO: 'No',
    CLOSE: 'Close',
    SHOW_MORE: 'Show more...',
    EDIT_SCRIPT: 'Edit Script:',
    SAVE_ENTITY: 'Save Entity',
    RUN_SCRIPT: 'Debug',
    ONLY_READ: 'Only Read',
    ADD_ENTITY: 'New Object',
    SEARCH: 'Filter...',
    DELETE_ENTITY: 'Delete Entity',
    DELETE_ENTITY_SHORT: 'Delete',
    CREATE_CHILDREN: 'Create Children',
    CREATE_ONE_CHILD: 'Create One Child',
    OTHERS_CAN: 'Others Can',
    CREATE: 'Create',
    CANCEL: 'Cancel',
    ALREADY_LOGGED_IN: 'Already logged in',
    TYPE: 'Type',
    STRING: 'String',
    REAL: 'Real',
    INT: 'Int',
    DESCRIPTION: 'Description',
    NO_ENTITY: 'No field exists',
    ADD_ROOT: 'New Root',
    ADD_FIELD: 'New Field',
    REFRESH: 'Refresh',
    SAVE: 'Save',
    SAVE_APP: 'Save',
    REFRESH_APP: 'Refresh',
    DELETE: 'Delete',
    DELETE_APP: 'Delete App',
    NEW_APP: 'New App',
    NEW_APP_WINDOW: 'New App',
    NAME: 'Name',
    LOGO_URL: 'Logo URL',
    SITE_URL: 'client URLs & IPs',
    SITE_URL_DESCRIPTION: 'IP and URL addresses of sites or apps witch should can access to data for write.',
    CLIENT_ID: 'API Key',
    CLIENT_ID_DESCRIPTION: 'Unique ID used on client side.',
    VALUE: 'Value',
    CHILD_PROTO: 'Child Proto',
    FIELDS: 'Fields',
    NO_FIELDS: 'No fields exists',
    NO_README: 'No description or README provided.',
    MY_APPS: 'My Apps',
    MY_DATA: 'My Data',
    SIGN_OUT: 'Sign out',
    CONNECT_TO_FACEBOOK: 'Connect through Facebook',
    CONNECT_TO_GOOGLE: 'Connect through Google',
    REALLY_DELETE: 'You really want delete this entity?',
    NO_DATA: 'You have no data',
    NO_APPS: 'You have no apps',
    NO_APPS_DESCRIPTION: '',
    NO_APPS_CREATE: 'Create first app!',
    DOCS: 'Documentation',
    DEMOS: 'Demos',
    GET_STARTED: 'Get Started',
    SIGN_IN: 'Sign In',
    NOTHING: 'Nothing',
    READ_AND_VIEW_CHILDREN: 'Read and view children',
    PROTO_IS_FIXED: 'Is Fixed',
    MAX_NUMBER_OF_CHILDREN: 'Children limit',
    EDIT_ENTITY: 'Edit',
    SAVE_ENTITY: 'Save',
    REFRESH_ENTITY: 'Refresh',
    CANCEL_ENTITY: 'View',
    SIGN_OUT: 'Log Out',
    SEARCH_BY_ROOTS: 'Search roots',
    SEARCH_BY_ENTITIES: 'Search',
    ADD_RESOURCE_WINDOW: 'New Resource',
    ADD_RESOURCE_FILE: 'File',
    ADD_RESOURCE_TYPE: 'Type',
    AVATAR: 'Avatar',
    IMAGE: 'Image',
    FILE: 'File',
    ROOT_FIELDS: {
      avatar: 'Icon',
      name: 'Name',
      tags: 'Tags',
      description: 'Description',
      websiteURL: 'Website URL',
      readme: 'README'
    },
    ROOT_FIELD_PLACEHOLDERS: {
      name: 'Human readable name of your root',
      tags: 'Keywords describing root',
      description: 'Main about root',
      websiteURL: 'Website where data of root are used',
      readme: 'Markdown-formatted text about the root'
    },
    ROOT_AVATAR_UPLOAD: 'Upload',
    ROOT_AVATAR_BROWSE: 'Browse',
    ROOT_AVATAR_REMOVE: 'Remove',
    SHOW_ACCESS_KEY: 'Show access key'
  },
  RU: {
    YES: 'Да',
    NO: 'Нет',
    CLOSE: 'Закр.',
    SHOW_MORE: 'Показать ещё...',
    EDIT_SCRIPT: 'Ред. скрипта:',
    SAVE_ENTITY: 'Сохранить элемент',
    RUN_SCRIPT: 'Отл.',
    ONLY_READ: 'Только читать',
    ADD_ENTITY: 'Новый объект',
    SEARCH: 'Фильтр...',
    DELETE_ENTITY: 'Удалить элемент',
    DELETE_ENTITY_SHORT: 'Удал.',
    CREATE_CHILDREN: 'Создавать дочерние элементы',
    CREATE_ONE_CHILD: 'Создать один дочерний элемент',
    OTHERS_CAN: 'Другие могут',
    CREATE: 'Создать',
    CANCEL: 'Отмена',
    ALREADY_LOGGED_IN: 'Уже в системе',
    TYPE: 'Тип',
    STRING: 'Строка',
    REAL: 'Число',
    INT: 'Целое число',
    DESCRIPTION: 'Описание',
    NO_ENTITY: 'Нет полей',
    ADD_ROOT: 'Нов. корень',
    ADD_FIELD: 'Нов. поле',
    REFRESH: 'Обновить',
    SAVE: 'Сохр.',
    SAVE_APP: 'Сохр.',
    REFRESH_APP: 'Обновить прил.',
    DELETE: 'Удал.',
    DELETE_APP: 'Удалить прил.',
    NEW_APP: 'Новое прил.',
    NEW_APP_WINDOW: 'Новое приложение',
    NAME: 'Имя',
    LOGO_URL: 'Лого',
    SITE_URL: 'IP и URL адреса',
    SITE_URL_DESCRIPTION: 'Разделенные знаком «;» IP и URL адреса с которых разрешен доступ',
    CLIENT_ID: 'Ключ API',
    CLIENT_ID_DESCRIPTION: '',
    VALUE: 'Значение',
    CHILD_PROTO: 'Прототип',
    FIELDS: 'Поля',
    NO_FIELDS: 'Нет ни одного поля',
    NO_README: 'Нет ни описания ни README.',
    MY_APPS: 'Мои приложения',
    MY_DATA: 'Мои данные',
    SIGN_OUT: 'Выход',
    CONNECT_TO_FACEBOOK: 'Войти через Facebook',
    CONNECT_TO_GOOGLE: 'Войти через Google',
    REALLY_DELETE: 'Вы действительно хотите удалить этот элемент?',
    NO_DATA: 'У вас нет данных',
    NO_APPS: 'У вас нет приложений',
    NO_APPS_DESCRIPTION: 'Если вам нужно чтобы ваш сайт имел доступ на запись к данным, ' +
                         'вам необходимо создать приложение. В настройках приложения вы ' +
                         'можете настроить права доступа к данным.',
    NO_APPS_CREATE: 'Создать приложение!',
    REALLY_DELETE_APP: 'Вы действительно хотите удалить это приложение?',
    DOCS: 'Документация',
    DEMOS: 'Примеры',
    GET_STARTED: 'Для начала',
    SIGN_IN: 'Войти',
    NOTHING: 'Ничего',
    READ_AND_VIEW_CHILDREN: 'Чтение и просм. доч. эл.',
    PROTO_IS_FIXED: 'Зафиксирован',
    MAX_NUMBER_OF_CHILDREN: 'Доч. эл-тов',
    EDIT_ENTITY: 'Ред.',
    SAVE_ENTITY: 'Сохр.',
    REFRESH_ENTITY: 'Обнов.',
    CANCEL_ENTITY: 'Пр.',
    SIGN_OUT: 'Выход',
    SEARCH_BY_ROOTS: 'Поиск по корням',
    SEARCH_BY_ENTITIES: 'Поиск по элементам',
    ADD_RESOURCE_WINDOW: 'Добавить ресурс',
    ADD_RESOURCE_FILE: 'Файл',
    ADD_RESOURCE_TYPE: 'Тип',
    AVATAR: 'Аватар',
    IMAGE: 'Картинка',
    FILE: 'Файл',
    ROOT_FIELDS: {
      avatar: 'Иконка',
      name: 'Имя',
      tags: 'Теги',
      description: 'Описание',
      websiteURL: 'Вебсайт',
      readme: 'README'
    },
    ROOT_FIELD_PLACEHOLDERS: {
      name: 'Наименование проекта',
      tags: 'Ключевые слова описывающие проект',
      description: 'Коротко о проекте',
      websiteURL: 'Сайт на котором используются данные',
      readme: 'Подробное описание в Markdown формате'
    },
    ROOT_AVATAR_UPLOAD: 'Загрузить',
    ROOT_AVATAR_BROWSE: 'Обзор',
    ROOT_AVATAR_REMOVE: 'Удалить',
    SHOW_ACCESS_KEY: 'Показать ключ доступа'
  }
};

var LANGUAGE = window.localStorage && window.localStorage.getItem('language') || 'EN';
var STRINGS = STRINGS_ON_DIFFERENT_LANGUAGES[LANGUAGE];
