var STRINGS_ON_DIFFERENT_LANGUAGES = {
  EN: {
    YES: 'Yes',
    NO: 'No',
    CLOSE: 'Close',
    SHOW_MORE: 'Show more...',
    EDIT_SCRIPT: 'Edit Script:',
    SAVE_ENTITY: 'Save Entity',
    RUN_SCRIPT: 'Run',
    ONLY_READ: 'Only Read',
    ADD_ENTITY: 'New Entity',
    SEARCH: 'Search...',
    DELETE_ENTITY: 'Delete Entity',
    DELETE_ENTITY_SHORT: 'Delete',
    CREATE_CHILDREN: 'Create Children',
    CREATE_ONE_CHILD: 'Create One Child',
    OTHERS_CAN: 'Others Can',
    CREATE: 'Create',
    CANCEL: 'Cancel',
    ALREADY_LOGGED_IN: 'Already logged in',
    TYPE: 'Type',
    STRING: 'String',
    REAL: 'Real',
    INT: 'Int',
    DESCRIPTION: 'Description',
    NO_ENTITY: 'No field exists',
    ADD_ROOT: 'New Root',
    ADD_FIELD: 'New Field',
    REFRESH: 'Refresh',
    SAVE: 'Save',
    SAVE_APP: 'Save',
    REFRESH_APP: 'Refresh',
    DELETE: 'Delete',
    DELETE_APP: 'Delete App',
    NEW_APP: 'New App',
    NAME: 'Name',
    LOGO_URL: 'Logo URL',
    SITE_URL: 'Site URL',
    CLIENT_ID: 'API Key',
    VALUE: 'Value',
    CHILD_PROTO: 'Child Proto',
    FIELDS: 'Fields',
    NO_FIELDS: 'No fields exists',
    MY_APPS: 'My Apps',
    MY_DATA: 'My Data',
    SIGN_OUT: 'Sign out',
    CONNECT_TO_FACEBOOK: 'Connect through Facebook',
    CONNECT_TO_GOOGLE: 'Connect through Google',
    REALLY_DELETE: 'You really want delete this entity?',
    NO_DATA: 'You have no data',
    NO_APPS: 'You have no apps',
    DOCS: 'Documentation',
    DEMOS: 'Demos',
    GET_STARTED: 'Get Started',
    SIGN_IN: 'Sign In',
    NOTHING: 'Nothing',
    READ_AND_VIEW_CHILDREN: 'Read and view children',
    PROTO_IS_FIXED: 'Is Fixed',
    MAX_NUMBER_OF_CHILDREN: 'Childrens',
    EDIT_ENTITY: 'Edit',
    SAVE_ENTITY: 'Save',
    REFRESH_ENTITY: 'Refresh',
    CANCEL_ENTITY: 'View',
    SIGN_OUT: 'Log Out',
    SEARCH_BY_ROOTS: 'Search by all roots...'
  },
  RU: {
    YES: 'Да',
    NO: 'Нет',
    CLOSE: 'Закр.',
    SHOW_MORE: 'Показать ещё...',
    EDIT_SCRIPT: 'Ред. скрипта:',
    SAVE_ENTITY: 'Сохранить элемент',
    RUN_SCRIPT: 'Вып.',
    ONLY_READ: 'Только читать',
    ADD_ENTITY: 'Новый эл-т',
    SEARCH: 'Поиск...',
    DELETE_ENTITY: 'Удалить элемент',
    DELETE_ENTITY_SHORT: 'Удал.',
    CREATE_CHILDREN: 'Создавать дочерние элементы',
    CREATE_ONE_CHILD: 'Создать один дочерний элемент',
    OTHERS_CAN: 'Другие могут',
    CREATE: 'Создать',
    CANCEL: 'Отмена',
    ALREADY_LOGGED_IN: 'Уже в системе',
    TYPE: 'Тип',
    STRING: 'Строка',
    REAL: 'Число',
    INT: 'Целое число',
    DESCRIPTION: 'Описание',
    NO_ENTITY: 'Нет полей',
    ADD_ROOT: 'Нов. корень',
    ADD_FIELD: 'Нов. поле',
    REFRESH: 'Обновить',
    SAVE: 'Сохр.',
    SAVE_APP: 'Сохр.',
    REFRESH_APP: 'Обновить прил.',
    DELETE: 'Удал.',
    DELETE_APP: 'Удалить прил.',
    NEW_APP: 'Новое прил.',
    NAME: 'Имя',
    LOGO_URL: 'Лого',
    SITE_URL: 'Сайт',
    CLIENT_ID: 'Ключ API',
    VALUE: 'Значение',
    CHILD_PROTO: 'Прот. доч. эл-та',
    FIELDS: 'Поля',
    NO_FIELDS: 'Нет ни одного поля',
    MY_APPS: 'Мои приложения',
    MY_DATA: 'Мои данные',
    SIGN_OUT: 'Выход',
    CONNECT_TO_FACEBOOK: 'Войти через Facebook',
    CONNECT_TO_GOOGLE: 'Войти через Google',
    REALLY_DELETE: 'Вы действительно хотите удалить этот элемент?',
    NO_DATA: 'У вас нет данных',
    NO_APPS: 'У вас нет приложений',
    REALLY_DELETE_APP: 'Вы действительно хотите удалить это приложение?',
    DOCS: 'Документация',
    DEMOS: 'Примеры',
    GET_STARTED: 'С чего начать',
    SIGN_IN: 'Войти',
    NOTHING: 'Ничего',
    READ_AND_VIEW_CHILDREN: 'Чтение и просм. доч. эл.',
    PROTO_IS_FIXED: 'Зафиксирован',
    MAX_NUMBER_OF_CHILDREN: 'Доч. эл-тов',
    EDIT_ENTITY: 'Ред.',
    SAVE_ENTITY: 'Сохр.',
    REFRESH_ENTITY: 'Обнов.',
    CANCEL_ENTITY: 'Пр.',
    SIGN_OUT: 'Выход',
    SEARCH_BY_ROOTS: 'Поиск по всем...'
  }
};


var LANGUAGE = window.localStorage && window.localStorage.getItem('language') || 'EN';
var STRINGS = STRINGS_ON_DIFFERENT_LANGUAGES[LANGUAGE];
