# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Data Space
email: support@my-data.space
baseurl: ""

url: "https://my-data.space"
enforce_ssl: my-data.space

api_url: "https://api.my-data.space"
api_websocket_url: "https://api.my-data.space:8443"
client_id: "a56e6a0c-06ab-bca7-bb97-18c8898c68f9"
github_username:  fiftin

# Build settings
markdown: kramdown

default_language: en

languages:
  - ru

exclude:
  - vendor/bootstrap/stylesheets
  - vendor/fa/scss
  - gulpfile.js
  - package.json
  - bower.json
  - node_modules
  - bower_components
  - README.md
  - jquery
