# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
project_name: web20

title: Web 2.0 site — Website builder made for developers
email: webmaster@web20.site
baseurl: ""

destination:     ./_site.web20
collections_dir: .
plugins_dir:     _plugins.web20
layouts_dir:     _layouts.web20
data_dir:        _data.web20
includes_dir:    _includes.web20



url: "https://web20.site"
enforce_ssl: web20.site

local_api_url: "https://localhost:8443"
local_cdn_url: "https://d10ztdrlkjcw7n.cloudfront.net"
local_api_websocket_url: "https://localhost:8443"
local_refine_url: "http://localhost:3333/"

api_url: "https://api.web20site.com"
cdn_url: "https://cdn.web20site.com"
api_websocket_url: "https://api.web20site.com"
refine_url: "https://refine.web20.site"

client_id: "4c0190a6-3f38-a21b-4391-eaaed8c7e1e2"
github_username:  fiftin

# Build settings
markdown: kramdown

default_language: en

languages:
  - ru

exclude:
  - test
  - vendor/bootstrap/stylesheets
  - vendor/fa/scss
  - gulpfile.js
  - package.json
  - bower.json
  - node_modules
  - bower_components
  - README.md
  - jquery
  - .git/*
