# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
project_name: mydataspace
title: MyDataSpace — Data Publishing Service
email: support@mydataspace.org
baseurl: ""

url: "https://mydataspace.org"
enforce_ssl: mydataspace.org

facebook_url: "https://www.facebook.com/mydataspace"
google_plus_url: "https://plus.google.com/communities/107145683419072073269"
github_url: "https://github.com/mydataspace"
codepen_url: "https://codepen.io/mydataspace"
angellist_url: "https://angel.co/my-data-space"
vk_url: "https://vk.com/mydataspace"
twitter_url: "https://twitter.com/mydataspace"
medium_ru_url: "https://medium.com/@mydataspace_ru"
zen_url: "https://zen.yandex.ru/media/id/5936e2b37ddde8524b45d05f"

local_api_url: "https://localhost:8443"
local_cdn_url: "https://d10ztdrlkjcw7n.cloudfront.net"
local_api_websocket_url: "https://localhost:8443"
local_refine_url: "http://localhost:3333/"

api_url: "https://api.mydataspace.net"
cdn_url: "https://cdn.mydataspace.net"
api_websocket_url: "https://api.mydataspace.net"
refine_url: "https://refine.mydataspace.org"

client_id: "a56e6a0c-06ab-bca7-bb97-18c8898c68f9"
github_username:  fiftin

# Build settings
markdown: kramdown

default_language: en

languages:
  - ru

exclude:
  - test
  - vendor/bootstrap/stylesheets
  - vendor/fa/scss
  - gulpfile.js
  - package.json
  - bower.json
  - node_modules
  - bower_components
  - README.md
  - jquery
  - .git/*
