# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
project_name: web20

title: Fastlix — Website builder made for developers
email: webmaster@web20.site
baseurl: ""

destination:     ./_site
#collections_dir: .
plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        _data
includes_dir:    _includes


facebook_url: https://www.facebook.com/web20site
github_url: "https://github.com/web20site"
vk_url: "https://vk.com/fastlix"
twitter_url: "https://twitter.com/fastlix"
zen_url: "https://zen.yandex.ru/media/id/5936e2b37ddde8524b45d05f"


url: "https://fastlix.com"
enforce_ssl: fastlix.com

local_api_url: "https://localhost:8443"
local_cdn_url: "https://d10ztdrlkjcw7n.cloudfront.net"
local_api_websocket_url: "https://localhost:8443"
local_refine_url: "http://localhost:3333/"

api_url: "https://api.web20site.com"
cdn_url: "https://cdn.web20site.com"
api_websocket_url: "https://api.web20site.com"
refine_url: "https://refine.fastlix.com"

client_id: "4c0190a6-3f38-a21b-4391-eaaed8c7e1e2"
github_username:  fiftin

# Build settings
markdown: kramdown

default_language: en

languages:
  - ru

exclude:
  #- js/search.js
  - js/webix_search.js
  #- js/ru/search.js
  - js/ru/webix_search.js
  #- search
  #- ru/search
  - test
  - vendor/bootstrap/stylesheets
  - vendor/fa/scss
  - gulpfile.js
  - package.json
  - bower.json
  - node_modules
  - bower_components
  - README.md
  - jquery
  - .git/*
  - .idea
  - "*.pug"
